# Use postgres/example user/password credentials
services:
  db:
    image: postgres:latest
    restart: always
    # set shared memory limit when using docker-compose
    # or set shared memory limit when deploy via swarm stack
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USER}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASS}
      POSTGRES_DB: ${SPRING_DATASOURCE_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
